# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\OneDrive\python\Electronic_Woodfish\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(477, 377)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 350, 350))
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/res/muyu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(300, 300))
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(350, 0, 125, 350))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 477, 27))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.actionNya = QtWidgets.QAction(MainWindow)
        self.actionNya.setObjectName("actionNya")
        self.action_no_auto = QtWidgets.QAction(MainWindow)
        self.action_no_auto.setCheckable(True)
        self.action_no_auto.setChecked(False)
        self.action_no_auto.setObjectName("action_no_auto")
        self.action_auto = QtWidgets.QAction(MainWindow)
        self.action_auto.setCheckable(True)
        self.action_auto.setChecked(False)
        self.action_auto.setObjectName("action_auto")
        self.menu.addAction(self.actionNya)
        self.menu_2.addAction(self.action_no_auto)
        self.menu_2.addAction(self.action_auto)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "电子木鱼 BY 雪中明月"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "TIP：点击左侧图标增加功德"))
        self.menu.setTitle(_translate("MainWindow", "开始"))
        self.menu_2.setTitle(_translate("MainWindow", "模式"))
        self.actionNya.setText(_translate("MainWindow", "Nya !"))
        self.action_no_auto.setText(_translate("MainWindow", "手动模式"))
        self.action_auto.setText(_translate("MainWindow", "自动模式"))
import res_rc
